# Generated by Django 5.0.6 on 2024-06-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0008_remove_user_role_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('driver', 'Driver'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
