# Generated by Django 5.0.6 on 2024-06-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0009_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('driver', 'Driver'), ('administrateur', 'Administrateur')], default='client', max_length=20),
        ),
    ]
