# Generated by Django 5.0.6 on 2024-06-28 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0014_alter_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='taxi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taxis.taxi'),
        ),
    ]
