# Generated by Django 5.0.6 on 2024-06-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0015_booking_taxi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='taxi',
        ),
    ]
