# Generated by Django 5.0.6 on 2024-06-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0016_remove_booking_taxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='taxis.driver'),
        ),
    ]
