# Generated by Django 5.0.6 on 2024-07-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0017_booking_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
