# Generated by Django 5.0.6 on 2024-07-01 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0018_driver_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxis.driver'),
        ),
    ]
